### ISSUE TITLE
Instructions for MS Edge

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/KnowledgeBase#113]
Check the PR here:
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/1143

Do we need to incorporate in in the new KB?

**Comment by JohnDoeIsBack** [comment]
Hi ameshkov, The instructions for Edge were severely outdated so I completely renewed them. Edge went through a engine change to chromium which also allows extensions from chrome to be added onto Edge so you can use either web stores to install Adguard extension (Microsoft edge add-ons/Chrome Web Store)

**Comment by ameshkov** [comment]
@JohnDoeIsBack hi! It's just we're about to make the new knowledge base available to general public and it may be newer than the old one:
https://adguard.com/kb/

**Comment by JohnDoeIsBack** [comment]
The new KB looks great, although the part where you can also add the same extension through chrome web store inside Edge can also be merged with it.. maybe some users don't want to rely on microsoft's store but google chrome's since the functionality stays the same.

I'll be glad if I contributed even a little to adguard :)

**Comment by ss-orlova** [comment]
Hello @JohnDoeIsBack,
I've updated the instructions based on your suggestions. You can have a look at this pull request: https://github.com/AdguardTeam/KnowledgeBase/pull/114
