### ISSUE TITLE
Apps to sleep

### ISSUE THREAD

**Issue by Bushido1** [AdguardTeam/KnowledgeBase#70]
Hi!
Please clarify if following the Samsung guide at https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/04.android/06.solving-problems/09.background-work/docs.en.md will disable the relevant options only for AdGuard and all the other apps may go to sleep. I would like to put other apps to sleep.

**Comment by zzebrum** [comment]
@Bushido1 hi! 

let's clarify the fact that our article was based on the information from [this website](https://dontkillmyapp.com/). And the original article have changed since we posted ours. We need to make some corrections as well.

1. disabling all toggles (step 4) **will affect all applications and battery consumption** in the system. I keep all toggles enabled (`Put unused apps to sleep`, `Auto-disable unused apps`, `Adaptive battery`) and have never experienced problems with the system killing AdGuard apps. 
2. waking up all apps (step 6) is obviously incorrect. you need to wake up only AdGuard and AdGuard VPN.

**Comment by aalpatkina** [comment]
@Bushido1 We have updated the article and taken all the corrections into account. It will soon be available in our new knowledge base.
