### ISSUE TITLE
Add an article about known compatibility issues with different Android apps

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/KnowledgeBase#79]
Here's the old content:
https://kb.adguard.com/en/android/faq#conflicts

The old article is outdated, we need assistance from the android team to compile the full list.

This article is linked from the Android app, we need to figure out for which apps we notify the user and lead to that article.

**Comment by admitrevskiy** [comment]
**Unsupported browsers**

| App name                | Package name                    | Filtering mode    |
|-------------------------|---------------------------------|-------------------|
| Opera mini              | com.opera.mini.android          | All               |
| Opera mini with Yandex  | com.opera.mini.android.yandex   | All               |
| UC Browser              | com.UCMobile.intl               | All               |
| UC Browser for x86      | com.UCMobile.intl.x86           | All               |
| UC Mini                 | com.uc.browser.en               | All               |
| UC Browser HD           | com.uc.browser.hd               | All               |
| Pufin Browser           | com.cloudmosa.puffinFree        | All               |
| Pufin Browser Pro       | com.cloudmosa.puffin            | All               |
| Dolphin Browser         | com.dolphin.browser             | Manual HTTP Proxy |
| Dolphin Browser Express | com.dolphin.browser.express.web | Manual HTTP Proxy |


**Conflict apps**

All VPN apps are incompatible with AdGuard running in VPN filtering mode since you cannot have two active VPNs at the same time.

First of all, it's best to use AdGuard VPN, since it has a compatibility mode with AdGuard out-of-the-box.

The second option is to use AdGuard in Local HTTP Proxy mode. Please note that 'manual' HTTP Proxy mode is broken since Android 10.

And the last one is to find out if third-party VPN app supports SOCKS4/SOCKS5 mode. In this case you can configure VPN app to work as outbound proxy and set up local-host outbound proxy with params from third-party app. AdGuard can be automatically configured with one of these applications: 'Orbot: Proxy with Tor'


**Samsung Pay**

The Samsung Pay app does not work due to the presence of an active VPN interface. 

This issue is region-specific and all known issues were reported by users from South Korea.

See https://github.com/AdguardTeam/AdguardForAndroid/issues/1209 for more details.


**Private DNS**

Private DNS was introduced in Android Pie. However, before version Q, the presence of a private DNS did not break our logic and DNS forwarding through AdGuard functioned normally.

Since version Q, the presence of a private DNS causes applications to redirect traffic through the system resolver, and not through AdGuard.

See Android devs blog for more details: https://android-developers.googleblog.com/2018/04/dns-over-tls-support-in-android-p.html

P.S. here is an interesting case. Some device manufacturers keep Private DNS settings hidden and set 'Automatic' mode as a default one. Thus, disabling the private DNS is impossible, but we can make the system think that the upstream is not valid. The system will use us as a bootstrap for the first host resolution and we can block it with $network rule. Thus, a failed bootstrap request causes the system to redirect DNS traffic through AdGuard.

**Comment by ameshkov** [comment]
Note that for Samsung Pay we have a separate article already and we don't need it here.

**Comment by ameshkov** [comment]
Unsupported browsers: we should explain what exactly is wrong with them.

* `UC-family browsers -- we actually CAN filter them. The problems may arise when these browsers are configured to use data compression. Need @AdguardTeam/qa-team to verify.
* `Opera mini` -- we cannot filter traffic due to the fact that it's compressed. Need @AdguardTeam/qa-team to verify.
* `Pufin Browser` -- we cannot filter traffic due to compression.
* `Dolphin Browser` -- we cannot filter its traffic when AdGuard is in "Manual proxy mode" because these browsers ignore system proxy settings.

**Comment by el-termikael** [comment]
https://github.com/AdguardTeam/KnowledgeBase/pull/83
